version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_ENV: production
      SECRET_KEY: 2Me7RCFDOB2BKdxKoRR5rshDwHH7EB6u
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://sentime_user:root_12345@db:5432/sentime
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis
  redis:
    image: redis
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: sentime
      POSTGRES_USER: sentime_user
      POSTGRES_PASSWORD: root_12345
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis-data: ~
  postgres: ~