FROM python:3.6.9

WORKDIR /usr/src

EXPOSE 5000

COPY ./requirements.txt .

RUN pip install -r requirements.txt

RUN python -m spacy download es_core_news_md

RUN pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint

COPY . .

CMD ["python3", "wsgi.py"]