FROM tensorflow/tensorflow:2.1.0-py3 as builder

FROM builder

WORKDIR /usr/src

EXPOSE 5000

COPY ./requirements.txt .

RUN pip3 install -r requirements.txt

RUN python -m spacy download es_core_news_md

COPY . .

CMD ["python3", "wsgi.py"]