"""empty message

Revision ID: 16287b443fb3
Revises: 07d947124ef4
Create Date: 2020-05-22 04:27:32.774707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16287b443fb3'
down_revision = '07d947124ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('results', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('searches', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('searches', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('searches', 'updated_at')
    op.drop_column('searches', 'created_at')
    op.drop_column('results', 'updated_at')
    op.drop_column('results', 'created_at')
    # ### end Alembic commands ###
